/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PosthocRouteImport } from './routes/posthoc'
import { Route as NarrationRouteImport } from './routes/narration'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as CbmRouteImport } from './routes/cbm'
import { Route as IndexRouteImport } from './routes/index'

const PosthocRoute = PosthocRouteImport.update({
  id: '/posthoc',
  path: '/posthoc',
  getParentRoute: () => rootRouteImport,
} as any)
const NarrationRoute = NarrationRouteImport.update({
  id: '/narration',
  path: '/narration',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const CbmRoute = CbmRouteImport.update({
  id: '/cbm',
  path: '/cbm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cbm': typeof CbmRoute
  '/evaluation': typeof EvaluationRoute
  '/narration': typeof NarrationRoute
  '/posthoc': typeof PosthocRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cbm': typeof CbmRoute
  '/evaluation': typeof EvaluationRoute
  '/narration': typeof NarrationRoute
  '/posthoc': typeof PosthocRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cbm': typeof CbmRoute
  '/evaluation': typeof EvaluationRoute
  '/narration': typeof NarrationRoute
  '/posthoc': typeof PosthocRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cbm' | '/evaluation' | '/narration' | '/posthoc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cbm' | '/evaluation' | '/narration' | '/posthoc'
  id: '__root__' | '/' | '/cbm' | '/evaluation' | '/narration' | '/posthoc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CbmRoute: typeof CbmRoute
  EvaluationRoute: typeof EvaluationRoute
  NarrationRoute: typeof NarrationRoute
  PosthocRoute: typeof PosthocRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/posthoc': {
      id: '/posthoc'
      path: '/posthoc'
      fullPath: '/posthoc'
      preLoaderRoute: typeof PosthocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/narration': {
      id: '/narration'
      path: '/narration'
      fullPath: '/narration'
      preLoaderRoute: typeof NarrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cbm': {
      id: '/cbm'
      path: '/cbm'
      fullPath: '/cbm'
      preLoaderRoute: typeof CbmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CbmRoute: CbmRoute,
  EvaluationRoute: EvaluationRoute,
  NarrationRoute: NarrationRoute,
  PosthocRoute: PosthocRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
